# Generated by Django 5.1.2 on 2024-11-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
