# Generated by Django 5.1.2 on 2024-10-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_collection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='items_in_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
