# Generated by Django 5.1.2 on 2024-12-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderitem_colors_orderitem_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sizes',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
