# Generated by Django 5.1.2 on 2025-01-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_orderitem_colors_remove_orderitem_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('vnpay', 'VNPay')], default='credit_card', max_length=20),
        ),
    ]
